services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: raj-portfolio-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/raj_portfolio
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo:8
    container_name: raj-portfolio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  mongo_data: